paths:
  guidelinescsv_file: "dataset/secure_coding_guidelines_M&C.csv"
  persist_dir: "chromaDB"
  code_output_dir: "output/rci_rag/gemini/sallms/code"
  prompt_dataset_file: "dataset/sallms.jsonl"
  prompt_file_dir: "output/rci_rag/gemini/sallms/prompts"
models:
  embedding_model: "text-embedding-3-small"

database:
  chunk_size: 1000
  chunk_overlap: 200 

misc:
  prompt_id_prefix: "rci_rag_" 
